# Dependencies
markdown:         redcarpet
highlighter:      pygments
gems: [jekyll-paginate, jekyll-gist]
paginate: 5
paginate_path: "page:num"

# Permalinks
permalink:        pretty

# Setup
title:            Amy Zhou
tagline:          'PS70 Documentation'
description:      'Welcome to my PS70 documentation site!'
url:              https://azhou4.github.io
baseurl:          /

author:
  name:           Amy Zhou


# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/azhou4/ps70/
