# Dependencies
markdown:         redcarpet
highlighter:      pygments
gems: [jekyll-paginate, jekyll-gist]
paginate: 5
paginate_path: "page:num"

# Permalinks
permalink:        pretty

# Setup
title:            Hyde
tagline:          'A Jekyll theme'
description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              https://azhou4.github.io
baseurl:          /

author:
  name:           Amy Zhou


# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/azhou4/ps70/
